package com.strichka.entity;

public enum GenreType {
  ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME,
  DOCUMENTARY, DRAMA, FAMILY, FANTASY, HISTORY, HORROR,
  MUSIC, MUSICAL, MYSTERY, ROMANCE, SPORT, SUPERHERO,
  THRILLER, WAR, WESTERN
}